name: thesis
dependencies:
  - python=3.6
  - tensorflow=1.13.1
  - numpy=1.16.*
  - pytest
  - pytest-runner
  - mypy
  - pip
  - pip:
    - pytest-mypy
    - pytest-flake8
    - gym[box2d]
    - git+git://github.com/deepmind/dm_control.git  # must be before planet
    - ./planet
