name: thesis
channels:
    - conda-forge
dependencies:
  - python=3.7
  - tensorflow-gpu=2.0.*
  - numpy=1.16.*
  - click
  - loguru
  - matplotlib
  - scikit-image
  - scipy
  - tensorflow-probability>=0.8
  - tqdm
  - ffmpeg  # needed to create gifs and videos
  - x264  # needed for mp4 videos with ffmpeg
  - moviepy  # needed to create gifs and videos

  # test dependencies
  - pytest
  - pytest-runner
  - mypy

  # habitat dependencies
  - attrs
  - imageio
  - imageio-ffmpeg
  - numba
  - pillow
  - pyglet
  - quaternion  # (numpy-quaternion)
  - requests
  - yacs

  # pip dependencies
  - pip
  - pip:
    - gin-config!=0.2.1
    - wandb

    # test
    - pytest-flake8
    - pytest-isort
    - pytest-mypy

    # planet
    - gym[box2d]==0.10.9
    - git+git://github.com/deepmind/dm_control.git

    # habitat
#    - git+git://github.com/facebookresearch/habitat-sim.git  # https://github.com/conda/conda/issues/9144
    - git+git://github.com/facebookresearch/habitat-api.git
