program: run.py
method: random
parameters:
  planet.max_epochs:
    value: 60
  planet.reward_loss_scale:
    distribution: q_log_uniform
    min: 0.0  # 1
    max: 4.61  # 100
  planet.model_size:
    distribution: q_log_uniform
    min: 4.61  # 100
    max: 5.992  # 400
  planet.state_size:
    distribution: q_log_uniform
    min: 3.0  # 20
    max: 4.1  # 60
  planet.num_layers:
    min: 1
    max: 3
  planet.num_units:
    distribution: q_log_uniform
    min: 4.61  # 100
    max: 6.215  # 500
